name: Check JSON Changes

on:
  schedule:
    - cron: "0 * * * *"  # Ejecuta cada hora
  workflow_dispatch:  # Permite ejecución manual

jobs:
  check-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          JSON_URL: ${{ secrets.JSON_URL }}
        run: python script.py